//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "content_type")]
pub enum ContentType {
    #[sea_orm(string_value = "bookmark")]
    Bookmark,
    #[sea_orm(string_value = "publication")]
    Publication,
    #[sea_orm(string_value = "unknown")]
    Unknown,
    #[sea_orm(string_value = "web_article")]
    WebArticle,
    #[sea_orm(string_value = "youtube_video")]
    YoutubeVideo,
}
