services:
  # reverse-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./infrastructure/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api-gateway
  #   networks:
  #     - pkms-network

  adminer:
    image: adminer
    restart: unless-stopped
    # ports:
    #   - 8080:8080
    networks:
      - pkms-network
  api-gateway:
    image: kong:latest
    restart: unless-stopped
    depends_on:
      - content-submission-service
      - content-processing-service
      - crawler-service
      - summarizer-service
      - embedding-service
    networks:
      - pkms-network
    environment:
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "10000:8000"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./infrastructure/api-gateway/kong.yml:/usr/local/kong/declarative/kong.yml:ro

  # auth-service:
  #   image: quay.io/keycloak/keycloak:26.0.0
  #   container_name: auth-service
  #   environment:
  #     - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN}
  #     - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
  #     - KC_DB=postgres
  #     - KC_DB_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
  #     - KC_DB_USERNAME=${POSTGRES_USER}
  #     - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
  #     - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
  #     - KC_HOSTNAME=http://localhost/auth
  #     - ENVIRONMENT=${ENVIRONMENT:-development}
  #   # ports:
  #   #   - "8080:8080"
  #   command:
  #     - start-dev
  #   depends_on:
  #     - postgres
  #   networks:
  #     - pkms-network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  content-submission-service:
    build:
      context: ./services/content-submission-service
      target: ${ENVIRONMENT}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      message-queue:
        condition: service_healthy
    networks:
      - pkms-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  content-processing-service:
    build:
      context: ./services/content-processing-service
      target: ${ENVIRONMENT}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      message-queue:
        condition: service_healthy
    networks:
      - pkms-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  crawler-service:
    build:
      context: ./services/crawler-service
      target: ${ENVIRONMENT}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      message-queue:
        condition: service_healthy
    networks:
      - pkms-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  summarizer-service:
    build:
      context: ./services/summarizer-service
      target: ${ENVIRONMENT}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      message-queue:
        condition: service_healthy
    networks:
      - pkms-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  embedding-service:
    build:
      context: ./services/embedding-service
      target: ${ENVIRONMENT}
    env_file:
      - .env
    depends_on:
      message-queue:
        condition: service_healthy
      pgvector:
        condition: service_healthy
    networks:
      - pkms-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  web-application:
    build:
      context: ./services/web-application/
    env_file:
      - .env
    # ports:
    #   - "3000:3000"
    networks:
      - pkms-network

  db-service:
    build:
      context: ./services/db-service
      target: ${ENVIRONMENT}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pkms-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  message-queue:
    image: rabbitmq:3-management
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    #   - "${RABBITMQ_PORT}:5672"
    #   - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - pkms-network

  # Database services
  postgres:
    image: postgres:13
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    # ports:
    #   - "${POSTGRES_PORT}:5432"
    networks:
      - pkms-network

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migration
    env_file:
      - .env
    command: -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB} -schemas=public -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -locations=filesystem:/flyway/sql -connectRetries=10 migrate
    volumes:
      - ./infrastructure/databases/postgres/migrations:/flyway/sql # where migration files are stored
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pkms-network

  pgvector:
    image: pgvector/pgvector:pg16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${VECTOR_DB_USER}
      - POSTGRES_PASSWORD=${VECTOR_DB_PASSWORD}
      - POSTGRES_DB=${VECTOR_DB_NAME}
    restart: unless-stopped
    volumes:
      - vector_db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${VECTOR_DB_USER} -d ${VECTOR_DB_NAME}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    # ports:
    #   - "${VECTOR_DB_PORT}:5432"
    networks:
      - pkms-network

  # qdrant:
  #   image: qdrant/qdrant:v1.1.1
  #   volumes:
  #     - qdrant_data:/qdrant/storage
  #   ports:
  #     - "${QDRANT_REST_PORT}:6333"
  #     - "${QDRANT_GRPC_PORT}:6334"
  #   networks:
  #     - pkms-network

  # neo4j:
  #   image: neo4j:4.4
  #   ports:
  #     - "${NEO4J_HTTP_PORT}:7474"   # HTTP
  #     - "${NEO4J_BOLT_PORT}:7687"   # Bolt
  #   environment:
  #     - NEO4J_AUTH=${NEO4J_AUTH}
  #   volumes:
  #     - neo4j_data:/data
  #   networks:
  #     - pkms-network

  # test-service:
  #   image: curlimages/curl
  #   networks:
  #     - pkms-network
  #   command: sleep infinity

networks:
  pkms-network:
    name: pkms-network

volumes:
  rabbitmq_data:
  postgres_data:
  vector_db_data:
  # qdrant_data:
  # neo4j_data:
