services:
  adminer:
    image: ghcr.io/shyim/adminerevo:latest
    restart: unless-stopped
    ports:
      - 10001:8080
    environment:
      - ADMINER_DISABLE_CSRF=true
    networks:
      - pkms-network

  api-gateway:
    image: kong:latest
    restart: unless-stopped
    depends_on:
      - content-submission-service
    networks:
      - pkms-network
    environment:
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "10000:8000"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./infrastructure/api-gateway/kong.yml:/usr/local/kong/declarative/kong.yml:ro

  content-submission-service:
    image: content-manager:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      message-queue:
        condition: service_healthy
      db-service:
        condition: service_healthy
    networks:
      - pkms-network
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  content-classifier-service:
    image: universal-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PROCESSOR_NAME: classifier
    depends_on:
      message-queue:
        condition: service_healthy
    networks:
      - pkms-network

  crawler-service:
    image: universal-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PROCESSOR_NAME: crawler
    depends_on:
      message-queue:
        condition: service_healthy
    networks:
      - pkms-network

  transcriber-service:
    image: universal-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PROCESSOR_NAME: transcriber
    depends_on:
      message-queue:
        condition: service_healthy
    networks:
      - pkms-network

  summarizer-service:
    image: universal-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PROCESSOR_NAME: summarizer
    depends_on:
      message-queue:
        condition: service_healthy
    networks:
      - pkms-network

  embedding-service:
    image: universal-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PROCESSOR_NAME: embedding
    depends_on:
      message-queue:
        condition: service_healthy
      pgvector:
        condition: service_healthy
    networks:
      - pkms-network

  notifier-service:
    image: universal-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PROCESSOR_NAME: notifier
    depends_on:
      message-queue:
        condition: service_healthy
    networks:
      - pkms-network

  web-application:
    build:
      context: ./services/web-application/
    env_file:
      - .env
    # ports:
    #   - "3000:3000"
    networks:
      - pkms-network

  db-service:
    build:
      context: ./services/db-service
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "10002:8000"
    networks:
      - pkms-network
    entrypoint:
      [
        "/usr/app/db_service-cli",
        "start",
        "-e",
        "production",
        "--binding",
        "0.0.0.0",
      ]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'printf \"GET /_health HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n\" > /dev/tcp/127.0.0.1/8000'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  message-queue:
    image: rabbitmq:3-management
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 5
    ports:
      # - "5672:5672"
      - "10003:15672"
    networks:
      - pkms-network

  # Database services
  postgres:
    image: postgres:13
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - pkms-network

  pgvector:
    image: pgvector/pgvector:pg16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${VECTOR_DB_USER}
      - POSTGRES_PASSWORD=${VECTOR_DB_PASSWORD}
      - POSTGRES_DB=${VECTOR_DB_NAME}
    restart: unless-stopped
    volumes:
      - vector_db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${VECTOR_DB_USER} -d ${VECTOR_DB_NAME}",
        ]
      interval: 30s
      timeout: 5s
      retries: 10
    # ports:
    #   - "${VECTOR_DB_PORT}:5432"
    networks:
      - pkms-network

  # qdrant:
  #   image: qdrant/qdrant:v1.1.1
  #   volumes:
  #     - qdrant_data:/qdrant/storage
  #   ports:
  #     - "${QDRANT_REST_PORT}:6333"
  #     - "${QDRANT_GRPC_PORT}:6334"
  #   networks:
  #     - pkms-network

  # neo4j:
  #   image: neo4j:4.4
  #   ports:
  #     - "${NEO4J_HTTP_PORT}:7474"   # HTTP
  #     - "${NEO4J_BOLT_PORT}:7687"   # Bolt
  #   environment:
  #     - NEO4J_AUTH=${NEO4J_AUTH}
  #   volumes:
  #     - neo4j_data:/data
  #   networks:
  #     - pkms-network

  # test-service:
  #   image: curlimages/curl
  #   networks:
  #     - pkms-network
  #   command: sleep infinity

networks:
  pkms-network:
    name: pkms-network

volumes:
  rabbitmq_data:
  postgres_data:
  vector_db_data:
  # qdrant_data:
  # neo4j_data:
