version: '3.8'

services:
  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
    networks:
      - pkms-network

  api-gateway:
    build: ./services/api-gateway
    depends_on:
      - auth-service
    networks:
      - pkms-network

  auth-service:
    build: ./services/auth-service
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8081:8080"
    networks:
      - pkms-network

  content-submission-service:
    build: ./services/content-submission-service
    depends_on:
      - message-queue
      - auth-service
    networks:
      - pkms-network

  web-article-processor:
    build: ./services/content-processing-service/web-article-processor
    depends_on:
      - message-queue
      - postgres
      - milvus
    networks:
      - pkms-network

  youtube-video-processor:
    build: ./services/content-processing-service/youtube-video-processor
    depends_on:
      - message-queue
      - postgres
      - milvus
    networks:
      - pkms-network

  notification-service:
    build: ./services/notification-service
    depends_on:
      - message-queue
      - auth-service
    networks:
      - pkms-network

  search-service:
    build: ./services/search-service
    depends_on:
      - postgres
      - milvus
      - neo4j
    networks:
      - pkms-network

  content-visualization-service:
    build: ./services/content-visualization-service
    depends_on:
      - postgres
    networks:
      - pkms-network

  web-application:
    build: ./services/web-application
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - pkms-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=pkms_user
      - POSTGRES_PASSWORD=pkms_pass
      - POSTGRES_DB=pkms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pkms-network

  milvus:
    image: milvusdb/milvus:v2.0.0
    volumes:
      - milvus_data:/var/lib/milvus
    networks:
      - pkms-network

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
    networks:
      - pkms-network

  message-queue:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pkms-network

networks:
  pkms-network:

volumes:
  postgres_data:
  milvus_data:
  neo4j_data:
