_format_version: "2.1"
_transform: true

services:
  - name: adminer
    url: http://adminer:8080
    routes:
      - name: adminer-route
        paths:
          - /adminer

  - name: db-service
    url: http://db-service:8000
    routes:
      - name: db-route
        paths:
          - /api/db

  - name: content-submission-service
    url: http://content-submission-service:8000
    routes:
      - name: content-submission-route
        paths:
          - /api/content-submission

  - name: web-application
    url: http://web-application:3000
    routes:
      - name: web-application
        paths:
          - /
        strip_path: true
        plugins:
          - name: basic-auth # Enable basic authentication plugin

plugins:
  - name: basic-auth
    service: web-application
    config:
      hide_credentials: true
  - name: key-auth
    service: content-submission-service
    config:
      key_names:
        - apikey
  # - name: cors
  #   config:
  #     origins:
  #       - http://localhost:10000
  #       - https://hub.fn2.run
  #     methods:
  #       - GET
  #       - POST
  #     headers:
  #       - Accept
  #       - Accept-Version
  #       - Content-Length
  #       - Content-MD5
  #       - Content-Type
  #       - Date
  #       - X-Auth-Token
  #     exposed_headers:
  #       - X-Auth-Token
  #     credentials: true
  #     max_age: 3600
  # - name: auth-service
  #   url: http://auth-service:8080
  #   routes:
  #     - name: auth
  #       paths:
  #         - /auth

consumers:
  - username: telegram_client # Create a consumer
    keyauth_credentials:
      - key: this_is_a_very_secret_key_for_telegram
  - username: neo
    basicauth_credentials:
      - username: neo
        password: lifeisgood
