_format_version: "2.1"
_transform: true

services:
  - name: db-service
    url: http://db-service:8000
    routes:
      - name: db-route
        paths:
          - /api/db

  - name: content-submission-service
    url: http://content-submission-service:8000
    routes:
      - name: content-submission-route
        paths:
          - /api/content-submission

  - name: content-processing-service
    url: http://content-processing-service:8000
    routes:
      - name: content-processing-route
        paths:
          - /api/content-processing

  - name: crawler-service
    url: http://crawler-service:8000
    routes:
      - name: crawler-route
        paths:
          - /api/crawler

  - name: summarizer-service
    url: http://summarizer-service:8000
    routes:
      - name: summarizer-route
        paths:
          - /api/summarizer

  - name: embedding-service
    url: http://embedding-service:8000
    routes:
      - name: embedding-route
        paths:
          - /api/embedding

  - name: web-application
    url: http://web-application:3000
    routes:
      - name: web-application
        paths:
          - /
        strip_path: true
        plugins:
          - name: basic-auth # Enable basic authentication plugin

plugins:
  - name: basic-auth
    service: web-application
    config:
      hide_credentials: true
  - name: key-auth
    service: content-submission-service
    config:
      key_names:
        - apikey
    # - name: auth-service
    #   url: http://auth-service:8080
    #   routes:
    #     - name: auth
    #       paths:
    #         - /auth
# plugins:
#   - name: cors
#     config:
#       origins:
#         - http://localhost:3000
#       methods:
#         - GET
#         - POST
#         - PUT
#         - DELETE
#         - OPTIONS
#       headers:
#         - Accept
#         - Authorization
#         - Content-Type
#       credentials: true
#       max_age: 3600

consumers:
  - username: telegram_client # Create a consumer
    keyauth_credentials:
      - key: this_is_a_very_secret_key_for_telegram
  - username: neo
    basicauth_credentials:
      - username: neo
        password: lifeisgood
