_format_version: "2.1"
_transform: true

services:
  - name: db-service
    url: http://db-service:8000
    routes:
      - name: db-route
        paths:
          - /api/db

  - name: content-submission-service
    url: http://content-submission-service:8000
    routes:
      - name: content-submission-route
        paths:
          - /api/content-submission

  - name: content-processing-service
    url: http://content-processing-service:8000
    routes:
      - name: content-processing-route
        paths:
          - /api/content-processing

  - name: crawler-service
    url: http://crawler-service:8000
    routes:
      - name: crawler-route
        paths:
          - /api/crawler

  # - name: auth-service
  #   url: http://auth-service:8080
  #   routes:
  #     - name: auth
  #       paths:
  #         - /auth

plugins:
  - name: cors
    config:
      origins:
        - http://localhost:3000
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
      credentials: true
      max_age: 3600
